### ISSUE TITLE
backend demo öneriler

### ISSUE THREAD

**Issue by abdullahbilgin** [karmaphp/backend-demo#1]
ustalar kolay gelsin proje adını api demo değilde daha orjinal bi isimde kullanabilirsiniz mesela ifframework gibi ve başlangıç halini diğer frameworklar gibi BaslangicController ve view e yönlendirilmiş şekilde mesajı view de verilebilir ve projeye bunun üzerinden gidilebilir tabiki benimki sadece temenni usta olan sizsiniz Rabbim kolaylık versin

**Comment by mzahirr** [comment]
Merhaba @abdullahbilgin  bey bu proje API projesi olduğundan dolayı View katmanını kullanmıyoruz. Bu projeye bir framework mantığında değilde bir yapı ve paketlerin birleşmesi mantığından bakmak gerekiyor. İsim konusunda haklısınız isim değiştirilebilir. Kullanırken takıldığınız yerler olursa sormaktan çekinmeyiniz.
